
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Unity.Burst;
using Unity.Collections;
using Unity.Jobs;
using Unity.Mathematics;

// Disable warnings due to naming with numeric types and generated members not being used
// ReSharper disable InconsistentNaming
// ReSharper disable MemberCanBePrivate.Global
// ReSharper disable UnassignedField.Global
// ReSharper disable UnusedType.Global

/// ParallelFor Jobs for simple addition of numbers to elements of NativeArrays.
/// Each numeric type of Unity.Mathematics is supported; double, float, int and uint.
/// Each dimension is supported 2,3,4,2x2,2x3,2x4, etc.
namespace InfPoints.Jobs 
{
    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_double : IJobParallelFor
    {
        [ReadOnly] public double NumberToAdd;
        public NativeArray<double> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_double2 : IJobParallelFor
    {
        [ReadOnly] public double2 NumberToAdd;
        public NativeArray<double2> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_double2x2 : IJobParallelFor
    {
        [ReadOnly] public double2x2 NumberToAdd;
        public NativeArray<double2x2> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_double2x3 : IJobParallelFor
    {
        [ReadOnly] public double2x3 NumberToAdd;
        public NativeArray<double2x3> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_double2x4 : IJobParallelFor
    {
        [ReadOnly] public double2x4 NumberToAdd;
        public NativeArray<double2x4> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_double3 : IJobParallelFor
    {
        [ReadOnly] public double3 NumberToAdd;
        public NativeArray<double3> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_double3x2 : IJobParallelFor
    {
        [ReadOnly] public double3x2 NumberToAdd;
        public NativeArray<double3x2> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_double3x3 : IJobParallelFor
    {
        [ReadOnly] public double3x3 NumberToAdd;
        public NativeArray<double3x3> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_double3x4 : IJobParallelFor
    {
        [ReadOnly] public double3x4 NumberToAdd;
        public NativeArray<double3x4> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_double4 : IJobParallelFor
    {
        [ReadOnly] public double4 NumberToAdd;
        public NativeArray<double4> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_double4x2 : IJobParallelFor
    {
        [ReadOnly] public double4x2 NumberToAdd;
        public NativeArray<double4x2> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_double4x3 : IJobParallelFor
    {
        [ReadOnly] public double4x3 NumberToAdd;
        public NativeArray<double4x3> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_double4x4 : IJobParallelFor
    {
        [ReadOnly] public double4x4 NumberToAdd;
        public NativeArray<double4x4> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_float : IJobParallelFor
    {
        [ReadOnly] public float NumberToAdd;
        public NativeArray<float> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_float2 : IJobParallelFor
    {
        [ReadOnly] public float2 NumberToAdd;
        public NativeArray<float2> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_float2x2 : IJobParallelFor
    {
        [ReadOnly] public float2x2 NumberToAdd;
        public NativeArray<float2x2> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_float2x3 : IJobParallelFor
    {
        [ReadOnly] public float2x3 NumberToAdd;
        public NativeArray<float2x3> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_float2x4 : IJobParallelFor
    {
        [ReadOnly] public float2x4 NumberToAdd;
        public NativeArray<float2x4> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_float3 : IJobParallelFor
    {
        [ReadOnly] public float3 NumberToAdd;
        public NativeArray<float3> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_float3x2 : IJobParallelFor
    {
        [ReadOnly] public float3x2 NumberToAdd;
        public NativeArray<float3x2> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_float3x3 : IJobParallelFor
    {
        [ReadOnly] public float3x3 NumberToAdd;
        public NativeArray<float3x3> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_float3x4 : IJobParallelFor
    {
        [ReadOnly] public float3x4 NumberToAdd;
        public NativeArray<float3x4> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_float4 : IJobParallelFor
    {
        [ReadOnly] public float4 NumberToAdd;
        public NativeArray<float4> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_float4x2 : IJobParallelFor
    {
        [ReadOnly] public float4x2 NumberToAdd;
        public NativeArray<float4x2> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_float4x3 : IJobParallelFor
    {
        [ReadOnly] public float4x3 NumberToAdd;
        public NativeArray<float4x3> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_float4x4 : IJobParallelFor
    {
        [ReadOnly] public float4x4 NumberToAdd;
        public NativeArray<float4x4> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_int : IJobParallelFor
    {
        [ReadOnly] public int NumberToAdd;
        public NativeArray<int> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_int2 : IJobParallelFor
    {
        [ReadOnly] public int2 NumberToAdd;
        public NativeArray<int2> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_int2x2 : IJobParallelFor
    {
        [ReadOnly] public int2x2 NumberToAdd;
        public NativeArray<int2x2> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_int2x3 : IJobParallelFor
    {
        [ReadOnly] public int2x3 NumberToAdd;
        public NativeArray<int2x3> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_int2x4 : IJobParallelFor
    {
        [ReadOnly] public int2x4 NumberToAdd;
        public NativeArray<int2x4> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_int3 : IJobParallelFor
    {
        [ReadOnly] public int3 NumberToAdd;
        public NativeArray<int3> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_int3x2 : IJobParallelFor
    {
        [ReadOnly] public int3x2 NumberToAdd;
        public NativeArray<int3x2> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_int3x3 : IJobParallelFor
    {
        [ReadOnly] public int3x3 NumberToAdd;
        public NativeArray<int3x3> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_int3x4 : IJobParallelFor
    {
        [ReadOnly] public int3x4 NumberToAdd;
        public NativeArray<int3x4> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_int4 : IJobParallelFor
    {
        [ReadOnly] public int4 NumberToAdd;
        public NativeArray<int4> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_int4x2 : IJobParallelFor
    {
        [ReadOnly] public int4x2 NumberToAdd;
        public NativeArray<int4x2> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_int4x3 : IJobParallelFor
    {
        [ReadOnly] public int4x3 NumberToAdd;
        public NativeArray<int4x3> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_int4x4 : IJobParallelFor
    {
        [ReadOnly] public int4x4 NumberToAdd;
        public NativeArray<int4x4> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_uint : IJobParallelFor
    {
        [ReadOnly] public uint NumberToAdd;
        public NativeArray<uint> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_uint2 : IJobParallelFor
    {
        [ReadOnly] public uint2 NumberToAdd;
        public NativeArray<uint2> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_uint2x2 : IJobParallelFor
    {
        [ReadOnly] public uint2x2 NumberToAdd;
        public NativeArray<uint2x2> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_uint2x3 : IJobParallelFor
    {
        [ReadOnly] public uint2x3 NumberToAdd;
        public NativeArray<uint2x3> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_uint2x4 : IJobParallelFor
    {
        [ReadOnly] public uint2x4 NumberToAdd;
        public NativeArray<uint2x4> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_uint3 : IJobParallelFor
    {
        [ReadOnly] public uint3 NumberToAdd;
        public NativeArray<uint3> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_uint3x2 : IJobParallelFor
    {
        [ReadOnly] public uint3x2 NumberToAdd;
        public NativeArray<uint3x2> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_uint3x3 : IJobParallelFor
    {
        [ReadOnly] public uint3x3 NumberToAdd;
        public NativeArray<uint3x3> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_uint3x4 : IJobParallelFor
    {
        [ReadOnly] public uint3x4 NumberToAdd;
        public NativeArray<uint3x4> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_uint4 : IJobParallelFor
    {
        [ReadOnly] public uint4 NumberToAdd;
        public NativeArray<uint4> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_uint4x2 : IJobParallelFor
    {
        [ReadOnly] public uint4x2 NumberToAdd;
        public NativeArray<uint4x2> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_uint4x3 : IJobParallelFor
    {
        [ReadOnly] public uint4x3 NumberToAdd;
        public NativeArray<uint4x3> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

    /// Add a number to every element of a NativeArray.
    /// The addition is done in place.
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct AdditionJob_uint4x4 : IJobParallelFor
    {
        [ReadOnly] public uint4x4 NumberToAdd;
        public NativeArray<uint4x4> Values;

        public void Execute(int index)
        {
            Values[index] += NumberToAdd;
        }
    }

}