
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using InfPoints.Jobs;
using NUnit.Framework;
using Unity.Collections;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Jobs;
using Unity.Mathematics;
using Unity.PerformanceTesting;

// Disable warnings due to naming with numeric types and generated members not being used
// ReSharper disable IdentifierTypo
// ReSharper disable InconsistentNaming
// ReSharper disable MemberCanBePrivate.Global
// ReSharper disable UnassignedField.Global
// ReSharper disable UnusedType.Global

namespace InfPoints.Tests.Editor.Jobs
{
    public class AddJobTests
    {

        [Test]
        [Performance]
        public void PerformanceAddingFloat()
        {
                const int valuesCount = 5_000_000;
                using (var values = new NativeArray<float>(valuesCount, Allocator.Persistent))
                {
                    Measure.Method(() =>
                    {
                        var addJob = new AdditionJob_float()
                        {
                            Values = values,
                            NumberToAdd = 5
                        };

                        var addJobHandle = addJob.Schedule(values.Length, 1024);
                        addJobHandle.Complete();
                    }).IterationsPerMeasurement(15).Run();
                }
        }
        
        [Test]
        [Performance]
        public void PerformanceAddingFloat4()
        {
            const int valuesCount = 5_000_000;
            using (var values = new NativeArray<float>(valuesCount, Allocator.Persistent))
            {
                var valuesWide = values.Reinterpret<float4>(UnsafeUtility.SizeOf<float>());
                Measure.Method(() =>
                {
                    var addJob = new AdditionJob_float4()
                    {
                        Values = valuesWide,
                        NumberToAdd = 5
                    };

                    var addJobHandle = addJob.Schedule(valuesWide.Length, 1024);
                    addJobHandle.Complete();
                }).IterationsPerMeasurement(15).Run();
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_double()
        {
            double[] values = new double[] {0, 1, 2};
            using (var valuesArray = new NativeArray<double>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_double()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_double2()
        {
            double2[] values = new double2[] {0, 1, 2};
            using (var valuesArray = new NativeArray<double2>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_double2()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_double2x2()
        {
            double2x2[] values = new double2x2[] {0, 1, 2};
            using (var valuesArray = new NativeArray<double2x2>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_double2x2()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_double2x3()
        {
            double2x3[] values = new double2x3[] {0, 1, 2};
            using (var valuesArray = new NativeArray<double2x3>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_double2x3()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_double2x4()
        {
            double2x4[] values = new double2x4[] {0, 1, 2};
            using (var valuesArray = new NativeArray<double2x4>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_double2x4()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_double3()
        {
            double3[] values = new double3[] {0, 1, 2};
            using (var valuesArray = new NativeArray<double3>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_double3()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_double3x2()
        {
            double3x2[] values = new double3x2[] {0, 1, 2};
            using (var valuesArray = new NativeArray<double3x2>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_double3x2()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_double3x3()
        {
            double3x3[] values = new double3x3[] {0, 1, 2};
            using (var valuesArray = new NativeArray<double3x3>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_double3x3()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_double3x4()
        {
            double3x4[] values = new double3x4[] {0, 1, 2};
            using (var valuesArray = new NativeArray<double3x4>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_double3x4()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_double4()
        {
            double4[] values = new double4[] {0, 1, 2};
            using (var valuesArray = new NativeArray<double4>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_double4()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_double4x2()
        {
            double4x2[] values = new double4x2[] {0, 1, 2};
            using (var valuesArray = new NativeArray<double4x2>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_double4x2()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_double4x3()
        {
            double4x3[] values = new double4x3[] {0, 1, 2};
            using (var valuesArray = new NativeArray<double4x3>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_double4x3()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_double4x4()
        {
            double4x4[] values = new double4x4[] {0, 1, 2};
            using (var valuesArray = new NativeArray<double4x4>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_double4x4()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_float()
        {
            float[] values = new float[] {0, 1, 2};
            using (var valuesArray = new NativeArray<float>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_float()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_float2()
        {
            float2[] values = new float2[] {0, 1, 2};
            using (var valuesArray = new NativeArray<float2>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_float2()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_float2x2()
        {
            float2x2[] values = new float2x2[] {0, 1, 2};
            using (var valuesArray = new NativeArray<float2x2>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_float2x2()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_float2x3()
        {
            float2x3[] values = new float2x3[] {0, 1, 2};
            using (var valuesArray = new NativeArray<float2x3>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_float2x3()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_float2x4()
        {
            float2x4[] values = new float2x4[] {0, 1, 2};
            using (var valuesArray = new NativeArray<float2x4>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_float2x4()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_float3()
        {
            float3[] values = new float3[] {0, 1, 2};
            using (var valuesArray = new NativeArray<float3>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_float3()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_float3x2()
        {
            float3x2[] values = new float3x2[] {0, 1, 2};
            using (var valuesArray = new NativeArray<float3x2>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_float3x2()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_float3x3()
        {
            float3x3[] values = new float3x3[] {0, 1, 2};
            using (var valuesArray = new NativeArray<float3x3>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_float3x3()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_float3x4()
        {
            float3x4[] values = new float3x4[] {0, 1, 2};
            using (var valuesArray = new NativeArray<float3x4>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_float3x4()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_float4()
        {
            float4[] values = new float4[] {0, 1, 2};
            using (var valuesArray = new NativeArray<float4>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_float4()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_float4x2()
        {
            float4x2[] values = new float4x2[] {0, 1, 2};
            using (var valuesArray = new NativeArray<float4x2>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_float4x2()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_float4x3()
        {
            float4x3[] values = new float4x3[] {0, 1, 2};
            using (var valuesArray = new NativeArray<float4x3>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_float4x3()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_float4x4()
        {
            float4x4[] values = new float4x4[] {0, 1, 2};
            using (var valuesArray = new NativeArray<float4x4>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_float4x4()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_int()
        {
            int[] values = new int[] {0, 1, 2};
            using (var valuesArray = new NativeArray<int>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_int()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_int2()
        {
            int2[] values = new int2[] {0, 1, 2};
            using (var valuesArray = new NativeArray<int2>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_int2()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_int2x2()
        {
            int2x2[] values = new int2x2[] {0, 1, 2};
            using (var valuesArray = new NativeArray<int2x2>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_int2x2()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_int2x3()
        {
            int2x3[] values = new int2x3[] {0, 1, 2};
            using (var valuesArray = new NativeArray<int2x3>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_int2x3()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_int2x4()
        {
            int2x4[] values = new int2x4[] {0, 1, 2};
            using (var valuesArray = new NativeArray<int2x4>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_int2x4()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_int3()
        {
            int3[] values = new int3[] {0, 1, 2};
            using (var valuesArray = new NativeArray<int3>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_int3()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_int3x2()
        {
            int3x2[] values = new int3x2[] {0, 1, 2};
            using (var valuesArray = new NativeArray<int3x2>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_int3x2()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_int3x3()
        {
            int3x3[] values = new int3x3[] {0, 1, 2};
            using (var valuesArray = new NativeArray<int3x3>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_int3x3()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_int3x4()
        {
            int3x4[] values = new int3x4[] {0, 1, 2};
            using (var valuesArray = new NativeArray<int3x4>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_int3x4()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_int4()
        {
            int4[] values = new int4[] {0, 1, 2};
            using (var valuesArray = new NativeArray<int4>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_int4()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_int4x2()
        {
            int4x2[] values = new int4x2[] {0, 1, 2};
            using (var valuesArray = new NativeArray<int4x2>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_int4x2()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_int4x3()
        {
            int4x3[] values = new int4x3[] {0, 1, 2};
            using (var valuesArray = new NativeArray<int4x3>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_int4x3()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_int4x4()
        {
            int4x4[] values = new int4x4[] {0, 1, 2};
            using (var valuesArray = new NativeArray<int4x4>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_int4x4()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_uint()
        {
            uint[] values = new uint[] {0, 1, 2};
            using (var valuesArray = new NativeArray<uint>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_uint()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_uint2()
        {
            uint2[] values = new uint2[] {0, 1, 2};
            using (var valuesArray = new NativeArray<uint2>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_uint2()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_uint2x2()
        {
            uint2x2[] values = new uint2x2[] {0, 1, 2};
            using (var valuesArray = new NativeArray<uint2x2>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_uint2x2()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_uint2x3()
        {
            uint2x3[] values = new uint2x3[] {0, 1, 2};
            using (var valuesArray = new NativeArray<uint2x3>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_uint2x3()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_uint2x4()
        {
            uint2x4[] values = new uint2x4[] {0, 1, 2};
            using (var valuesArray = new NativeArray<uint2x4>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_uint2x4()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_uint3()
        {
            uint3[] values = new uint3[] {0, 1, 2};
            using (var valuesArray = new NativeArray<uint3>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_uint3()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_uint3x2()
        {
            uint3x2[] values = new uint3x2[] {0, 1, 2};
            using (var valuesArray = new NativeArray<uint3x2>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_uint3x2()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_uint3x3()
        {
            uint3x3[] values = new uint3x3[] {0, 1, 2};
            using (var valuesArray = new NativeArray<uint3x3>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_uint3x3()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_uint3x4()
        {
            uint3x4[] values = new uint3x4[] {0, 1, 2};
            using (var valuesArray = new NativeArray<uint3x4>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_uint3x4()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_uint4()
        {
            uint4[] values = new uint4[] {0, 1, 2};
            using (var valuesArray = new NativeArray<uint4>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_uint4()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_uint4x2()
        {
            uint4x2[] values = new uint4x2[] {0, 1, 2};
            using (var valuesArray = new NativeArray<uint4x2>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_uint4x2()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_uint4x3()
        {
            uint4x3[] values = new uint4x3[] {0, 1, 2};
            using (var valuesArray = new NativeArray<uint4x3>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_uint4x3()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }

        [Test]
        public void AddingGivesTheCorrectResult_uint4x4()
        {
            uint4x4[] values = new uint4x4[] {0, 1, 2};
            using (var valuesArray = new NativeArray<uint4x4>(values, Allocator.Persistent))
            {
                var addJob = new AdditionJob_uint4x4()
                {
                    Values = valuesArray,
                    NumberToAdd = 5
                };

                var addJobHandle = addJob.Schedule(values.Length, 1024);
                addJobHandle.Complete();

                for (int i = 0; i < values.Length; i++)
                {
                    Assert.That(valuesArray[i], Is.EqualTo(values[i]+addJob.NumberToAdd));
                }
            }
        }
    }
}